version: '3'

services:
  db:
    container_name: mariadb.musicmark.prod
    hostname: mariadb_local
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'musicmark'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3377:3306'
    restart: on-failure
    volumes:
      - './volumes/mysql/default:/var/lib/mysql'
    networks:
      - musicmark_network

  app:
    container_name: spring-boot.musicmark.prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "9061:9061"
    depends_on:
      - db
    restart: on-failure
    networks:
      - musicmark_network

networks:
  musicmark_network: